# Copyright by Lars Geyer-Blaumeiser <lars@lgblaumeiser.de>
#
# Licensed under MIT license
#
# SPDX-License-Identifier: MIT

version: '3.7'

volumes:
  PTMDataStore:

services:
  ptm:
    image: de.lgblaumeiser/ptm
    ports:
    - 27727:8080
    volumes:
    - PTMDataStore:/var/ptm
